import Foundation

public struct PrivacyFilter: Sendable {
  public var privacyMode: Bool
  public var ignoredApps: Set<String>
  public var ignoredPasteboardTypes: Set<String>

  public init(
    privacyMode: Bool = false,
    ignoredApps: Set<String> = Self.defaultIgnoredApps,
    ignoredPasteboardTypes: Set<String> = Self.defaultIgnoredPasteboardTypes
  ) {
    self.privacyMode = privacyMode
    self.ignoredApps = ignoredApps
    self.ignoredPasteboardTypes = ignoredPasteboardTypes
  }

  public func shouldRecord(sourceAppBundleId: String?, pasteboardTypes: Set<String>) -> Bool {
    if privacyMode {
      return false
    }

    if let sourceAppBundleId, ignoredApps.contains(sourceAppBundleId) {
      return false
    }

    if !pasteboardTypes.isDisjoint(with: ignoredPasteboardTypes) {
      return false
    }

    return true
  }

  public static let defaultIgnoredPasteboardTypes: Set<String> = [
    "com.apple.finder.node",
    "com.apple.is-remote-clipboard",
    "com.apple.pasteboard.promised-file-url",
    "com.apple.webarchive",
    "com.apple.flat-rtfd",
    "com.agilebits.onepassword",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.source"
  ]

  public static let defaultIgnoredApps: Set<String> = [
    "com.1password.1password",
    "com.agilebits.onepassword",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "com.dashlane.dashlanephonefinal",
    "com.lastpass.LastPass",
    "com.apple.keychainaccess",
    "org.keepassxc.keepassxc"
  ]
}
